[build]
  command = "ng build --configuration=production"
  publish = "dist/EndOfProgramWeb/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
